server:
  port: 9090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # Auth Service
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
        # Admin Service (Auth Service)
        - id: admin-service
          uri: http://localhost:8081
          predicates:
          - Path=/admin/**
          filters:
          - StripPrefix=0

        # Super Admin Service (Auth Service)
        - id: super-admin-service
          uri: http://localhost:8081
          predicates:
            - Path=/super-admin/**
          filters:
            - StripPrefix=0

        # User Service - Users, Companies, Drivers
        - id: user-service-users
          uri: http://localhost:7081
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=0

        - id: user-service-companies
          uri: http://localhost:7081
          predicates:
            - Path=/companies/**
          filters:
            - StripPrefix=0

        - id: user-service-drivers
          uri: http://localhost:7081
          predicates:
            - Path=/drivers/**
          filters:
            - RewritePath=/drivers/(.*), /companies/drivers/$1

        # Vehicle Service - Buses and Vehicles
        - id: vehicle-service-buses
          uri: http://localhost:7082
          predicates:
            - Path=/buses/**
          filters:
            - StripPrefix=0

        - id: vehicle-service-vehicles
          uri: http://localhost:7082
          predicates:
            - Path=/vehicles/**
          filters:
            - StripPrefix=0

        - id: vehicle-service-seats-bus
          uri: http://localhost:7082
          predicates:
            - Path=/seats/bus/**
          filters:
            - StripPrefix=0

        # Route Service
        - id: route-service
          uri: http://localhost:7083
          predicates:
            - Path=/routes/**
          filters:
            - StripPrefix=0

        # Schedule Service
        - id: schedule-service
          uri: http://localhost:7084
          predicates:
            - Path=/schedules/**
          filters:
            - StripPrefix=0

        # Seat Inventory Service
        - id: seat-inventory-service
          uri: http://localhost:7085
          predicates:
            - Path=/seats/lock,/seats/unlock,/seats/availability/**
          filters:
            - StripPrefix=0

        # Booking Service
        - id: booking-service
          uri: http://localhost:7086
          predicates:
            - Path=/bookings/**
          filters:
            - StripPrefix=0

        # Payment Service
        - id: payment-service
          uri: http://localhost:7087
          predicates:
            - Path=/payments/**
          filters:
            - StripPrefix=0

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: BusApp_JWT_Secret_2026_StrongKey_9fA7xL2PqR8MZK

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.gateway.gateway: DEBUG
